# Generated by Django 6.0.6 on 2026-06-19 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NoteMypage',
            fields=[
                ('note_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('modified_at', models.DateTimeField()),
                ('title', models.CharField(max_length=50)),
                ('era', models.CharField(blank=True, max_length=50, null=True)),
                ('topic', models.CharField(blank=True, max_length=50, null=True)),
                ('difficulty', models.CharField(blank=True, max_length=50, null=True)),
                ('question_type', models.CharField(blank=True, max_length=20, null=True)),
                ('content', models.TextField()),
                ('answer_no', models.IntegerField(blank=True, null=True)),
                ('answer_explanation', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'note_mypage',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudyPlanMypage',
            fields=[
                ('studyplan_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('study_plans', models.TextField(blank=True, null=True)),
                ('study_plan_items', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('modified_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'study_plan_mypage',
                'managed': False,
            },
        ),
    ]
