# Generated by Django 6.0.6 on 2026-07-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Analytics",
            fields=[
                ("analytics_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("analysis_scope", models.CharField(default="session", max_length=30)),
                ("analysis_run_id", models.CharField(max_length=36)),
                ("analysis_unit", models.CharField(max_length=30)),
                ("key_concept", models.CharField(max_length=50)),
                ("classification", models.CharField(max_length=20)),
                ("avg_time_sec", models.IntegerField(blank=True, null=True)),
                ("topic_rate", models.FloatField()),
                ("total_count", models.IntegerField(default=0)),
                ("correct_count", models.IntegerField(default=0)),
                ("wrong_count", models.IntegerField(default=0)),
                ("answer_rate", models.FloatField(default=0)),
                ("wrong_rate", models.FloatField(default=0)),
                ("period_start", models.DateField(blank=True, null=True)),
                ("period_end", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "db_table": "analytics",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="MlTrendTop5",
            fields=[
                ("trend_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("target_round", models.IntegerField()),
                ("recent5_rounds", models.CharField(max_length=20)),
                ("source", models.CharField(max_length=50)),
                ("source_name", models.CharField(blank=True, max_length=100, null=True)),
                ("usage_text", models.CharField(blank=True, max_length=255, null=True)),
                ("trend_type", models.CharField(max_length=50)),
                ("rank_no", models.IntegerField()),
                ("era", models.CharField(blank=True, max_length=50, null=True)),
                ("topic_train", models.CharField(blank=True, max_length=50, null=True)),
                ("topic", models.CharField(blank=True, max_length=50, null=True)),
                ("topic_summary", models.CharField(blank=True, max_length=255, null=True)),
                ("label", models.CharField(blank=True, max_length=100, null=True)),
                ("combo_label", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "combo_label_with_topic",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("count_value", models.IntegerField()),
                ("ratio", models.FloatField(blank=True, null=True)),
                ("ratio_percent", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "db_table": "ml_trend_top5",
                "managed": False,
            },
        ),
    ]
