# Generated by Django 6.0.6 on 2026-06-19 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analytics',
            fields=[
                ('analytics_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('key_concept', models.CharField(max_length=50)),
                ('classification', models.CharField(max_length=20)),
                ('avg_time_sec', models.IntegerField(blank=True, null=True)),
                ('topic_rate', models.FloatField()),
                ('date', models.DateTimeField()),
            ],
            options={
                'db_table': 'analytics',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QuestionOptions',
            fields=[
                ('choice_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('choice_no', models.IntegerField()),
                ('content', models.TextField()),
                ('is_answer', models.BooleanField()),
                ('choice_explanation', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'question_options',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('question_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('q_score', models.IntegerField()),
                ('era', models.CharField(max_length=50)),
                ('topic', models.CharField(max_length=50)),
                ('question_type', models.CharField(max_length=20)),
                ('content', models.TextField()),
                ('answer_no', models.IntegerField()),
                ('answer_explanation', models.TextField()),
                ('core_concept', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'questions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SolveRecords',
            fields=[
                ('record_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('selected_no', models.IntegerField(blank=True, null=True)),
                ('is_correct', models.BooleanField()),
                ('time_spent_sec', models.IntegerField(blank=True, null=True)),
                ('q_type', models.CharField(max_length=20)),
                ('topic', models.CharField(max_length=50)),
                ('era', models.CharField(max_length=20)),
                ('q_score', models.IntegerField()),
            ],
            options={
                'db_table': 'solve_records',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SolveSessions',
            fields=[
                ('session_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('session_type', models.CharField(max_length=20)),
                ('total_count', models.IntegerField()),
                ('elapsed_sec', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(max_length=20)),
                ('answer_rate', models.FloatField(blank=True, null=True)),
                ('total_score', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'solve_sessions',
                'managed': False,
            },
        ),
    ]
