"""
Django settings for config project.

Generated by 'django-admin startproject'. Current runtime: Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR.parent / '.env')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ['DJANGO_SECRET_KEY']

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DJANGO_DEBUG", "false").lower() == "true"

ALLOWED_HOSTS = [
    host.strip()
    for host in os.getenv("DJANGO_ALLOWED_HOSTS", "").split(",")
    if host.strip()
]

DJANGO_HEALTHCHECK_HOST = os.getenv(
    "DJANGO_HEALTHCHECK_HOST",
    "",
).strip()
if DJANGO_HEALTHCHECK_HOST and DJANGO_HEALTHCHECK_HOST not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(DJANGO_HEALTHCHECK_HOST)

CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.getenv("DJANGO_CSRF_TRUSTED_ORIGINS", "").split(",")
    if origin.strip()
]


def env_bool(name: str, default: bool) -> bool:
    return os.getenv(name, "true" if default else "false").lower() == "true"


SECURE_PROXY_SSL_HEADER = None
if env_bool("DJANGO_TRUST_X_FORWARDED_PROTO", False):
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# 보안 기본값은 운영(DEBUG=False)에서 켜진 상태가 되도록 DEBUG 반대값을 쓴다.
# 로컬 개발(DEBUG=True)은 http 라 기본이 꺼져 있고, 필요하면 env 로 개별 조정한다.
secure_default = not DEBUG
SECURE_SSL_REDIRECT = env_bool("DJANGO_SECURE_SSL_REDIRECT", secure_default)
# 헬스체크는 내부 http 로 들어오므로 https 강제 리다이렉트에서 제외한다.
SECURE_REDIRECT_EXEMPT = [r"^health/"]
SESSION_COOKIE_SECURE = env_bool("DJANGO_SESSION_COOKIE_SECURE", secure_default)
# Keep authentication short-lived on shared computers; closing the browser drops the cookie.
SESSION_COOKIE_AGE = 60 * 60 * 8
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
CSRF_COOKIE_SECURE = env_bool("DJANGO_CSRF_COOKIE_SECURE", secure_default)
# 운영 기본 1년. 서브도메인·preload 는 되돌리기 어려워 opt-in 으로 남긴다.
default_hsts_seconds = 31536000 if secure_default else 0
SECURE_HSTS_SECONDS = int(
    os.getenv("DJANGO_SECURE_HSTS_SECONDS", str(default_hsts_seconds))
)
SECURE_HSTS_INCLUDE_SUBDOMAINS = env_bool(
    "DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS", False
)
SECURE_HSTS_PRELOAD = env_bool("DJANGO_SECURE_HSTS_PRELOAD", False)

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'user',
    'pages',
    'chatbot',
    'analytics',
    'diagnosis',
    'question',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Gunicorn/ECS 환경에서도 처리되지 않은 요청 예외와 traceback을 stderr로 남긴다.
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'django.request': {
            'handlers': ['console'],
            'level': 'ERROR',
            'propagate': False,
        },
    },
}

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ['POSTGRES_DB'],
        'USER': os.environ['POSTGRES_USER'],
        # 기본값을 두지 않는다. 미주입 시 약한 고정 계정으로 붙는 것을 막기 위해
        # 환경변수가 없으면 기동 단계에서 실패시킨다.
        'PASSWORD': os.environ['POSTGRES_PASSWORD'],
        'HOST': os.getenv('POSTGRES_HOST', 'localhost'),
        'PORT': os.getenv('POSTGRES_PORT', '5432'),
        # Aurora Serverless v2 auto-pause를 방해하지 않도록 운영 기본값도 0으로 둔다.
        'CONN_MAX_AGE': int(os.getenv('POSTGRES_CONN_MAX_AGE', '0')),
        'OPTIONS': {
            'connect_timeout': int(
                os.getenv('POSTGRES_CONNECT_TIMEOUT_SECONDS', '30')
            ),
            'sslmode': os.getenv('POSTGRES_SSLMODE', 'prefer'),
            **(
                {
                    'sslrootcert': os.environ['POSTGRES_SSLROOTCERT'],
                }
                if os.getenv('POSTGRES_SSLROOTCERT')
                else {}
            ),
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']

STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# 워커 간 공유가 필요한 레이트리밋·헬스 캐시용.
# Redis 없이 기존 Postgres 에 캐시 테이블(himate_cache)을 둔다.
# LocMemCache 와 달리 gunicorn 워커 전체가 같은 카운터를 본다.
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
        'LOCATION': 'himate_cache',
    },
    # 준비 상태 캐시는 PostgreSQL을 사용하지 않는다. DB 캐시를 사용하면
    # /health/ 호출 자체가 Aurora Serverless의 auto-pause를 방해할 수 있다.
    'healthcheck': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'himate-healthcheck',
    },
}

# DRF 기본 권한을 인증 필수로 둔다. 게스트 공개 엔드포인트만 뷰에서
# @permission_classes([AllowAny]) 로 명시적으로 연다. 이렇게 하면 새 API 가
# 권한을 빠뜨려도 기본이 차단이라 안전하다.
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
    # 미인증 요청을 403 대신 401 로 반환해 프런트의 로그인 유도와 맞춘다.
    'EXCEPTION_HANDLER': 'config.drf.api_exception_handler',
}

AUTHENTICATION_BACKENDS = [
    'user.backends.UserAccountsBackend',
    'django.contrib.auth.backends.ModelBackend',
]

LOGIN_URL = '/user/login/'
LOGIN_REDIRECT_URL = '/analytics/mypage/'
LOGOUT_REDIRECT_URL = '/'

EMAIL_BACKEND = os.getenv(
    'EMAIL_BACKEND',
    'django.core.mail.backends.console.EmailBackend',
)
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'himate@example.com')
EMAIL_HOST = os.getenv('EMAIL_HOST', '')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'true').lower() == 'true'
