# Generated by Django 6.0.6 on 2026-06-19 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessages',
            fields=[
                ('message_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sender_type', models.CharField(max_length=10)),
                ('content', models.TextField()),
                ('used_tokens', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'chat_messages',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ChatSessions',
            fields=[
                ('session_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('chat_type', models.CharField(max_length=20)),
                ('turn_count', models.IntegerField()),
                ('status', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'chat_sessions',
                'managed': False,
            },
        ),
    ]
