"""Rule-based study plan calculation and persistence services."""

from analytics.service.study_plan.config import StudyPlanConfig, get_study_plan_config
from analytics.service.study_plan.planner import (
    PlanPeriod,
    PlanTarget,
    PriorityTarget,
    QuestionPoolInsufficient,
    StudyPlanPeriodUnavailable,
    build_plan_draft,
    build_priority_targets,
    calculate_daily_block_minutes,
    calculate_plan_period,
    calculate_score_counts,
    is_question_pool_available,
)
from analytics.service.study_plan.dto import build_study_plan_dto, parse_plan_items
from analytics.service.study_plan.service import (
    StudyPlanBlockNotDue,
    StudyPlanBlockNotFound,
    StudyPlanBlockRouteMismatch,
    StudyPlanBlockTerminal,
    StudyPlanDataIntegrityError,
    InitialStudyPlanConfigUnavailable,
    build_user_plan_draft,
    complete_study_plan_block_by_id,
    create_personalized_study_plan,
    finalize_plan_draft,
    get_active_study_plan_dto,
    is_weekly_review_plan_block,
    synchronize_plan_items,
    synchronize_active_study_plan,
    validate_block_start,
    validate_study_plan_block_start,
    validate_plan_items_for_mutation,
)

__all__ = [
    "PlanPeriod",
    "PlanTarget",
    "PriorityTarget",
    "QuestionPoolInsufficient",
    "InitialStudyPlanConfigUnavailable",
    "StudyPlanBlockNotDue",
    "StudyPlanBlockNotFound",
    "StudyPlanBlockRouteMismatch",
    "StudyPlanBlockTerminal",
    "StudyPlanConfig",
    "StudyPlanDataIntegrityError",
    "StudyPlanPeriodUnavailable",
    "build_plan_draft",
    "build_priority_targets",
    "build_study_plan_dto",
    "build_user_plan_draft",
    "calculate_daily_block_minutes",
    "calculate_plan_period",
    "calculate_score_counts",
    "complete_study_plan_block_by_id",
    "create_personalized_study_plan",
    "finalize_plan_draft",
    "get_active_study_plan_dto",
    "get_study_plan_config",
    "is_question_pool_available",
    "is_weekly_review_plan_block",
    "parse_plan_items",
    "synchronize_plan_items",
    "synchronize_active_study_plan",
    "validate_block_start",
    "validate_study_plan_block_start",
    "validate_plan_items_for_mutation",
]
