# Generated by Django 6.0.6 on 2026-07-29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("user", "0001_widen_verification_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailVerificationCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(db_index=True, max_length=255)),
                ("code", models.CharField(max_length=128)),
                ("purpose", models.CharField(default="register", max_length=20)),
                ("is_used", models.BooleanField(default=False)),
                ("attempt_count", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("used_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "email_verification_codes",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="UserAccounts",
            fields=[
                ("user_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("email", models.CharField(max_length=255, unique=True)),
                ("password_hash", models.CharField(max_length=255)),
                ("nickname", models.CharField(blank=True, max_length=50, null=True)),
                ("login_fail_count", models.IntegerField(default=0)),
                ("is_locked", models.BooleanField(default=False)),
                ("locked_at", models.DateTimeField(blank=True, null=True)),
                ("last_login", models.DateTimeField(blank=True, null=True)),
                ("status", models.CharField(default="active", max_length=20)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "daily_available_hours",
                    models.DecimalField(decimal_places=1, default=1.0, max_digits=3),
                ),
                ("exam_date", models.DateField(blank=True, null=True)),
            ],
            options={
                "db_table": "user_accounts",
                "managed": False,
            },
        ),
    ]
